### ISSUE TITLE
It wont work or setup

### ISSUE THREAD

**Issue by RNGTayblox** [jh220de/ccbot#48]
**Describe the bug**
If you have an error ID, please include it here or in the title.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![Screenshot 2022-08-13 5 44 46 PM](https://user-images.githubusercontent.com/111194128/184503235-58cdef13-bd5b-4a27-85a4-6abbd7fc32a1.png)

**Comment by nsde** [comment]
The project isn't actively maintained at this moment, but @JH220 told me he's planning to work on it again soon.
