### ISSUE TITLE
The application did not respond

### ISSUE THREAD

**Issue by GabrielVergara** [jh220de/ccbot#50]
Describe the bug
Attempted to run /clearall and /clear target and got this as a response on both.

To Reproduce

Go to any channel
Click on 'use slash command'
Scroll down to '/clear all' or '/clear > target'
(wait a moment)
See error

ClearChat Bot
BOT
 — Today at 00:25
The application did not respond
Only you can see this • Dismiss message

Expected behavior
it should clear all messages in chat
![image](https://user-images.githubusercontent.com/49233871/187788000-15f1c402-ab94-4a7c-b185-1d0882634619.png)

**Comment by madmikeymike** [comment]
Also suffering from this - Any updates?

**Comment by nsde** [comment]
The project isn't actively maintained at this moment, but @JH220 told me he's planning to work on it again soon.
