### ISSUE TITLE
Interaction-ID: 

### ISSUE THREAD

**Issue by Adriannoren** [jh220de/ccbot#52]
![proof2](https://user-images.githubusercontent.com/126923321/222852216-a351d552-4f20-4bbd-9181-d0a9e44b0d23.png)
![proof](https://user-images.githubusercontent.com/126923321/222852236-b7008675-d75b-4f73-882f-33af3c207ad0.png)
so it says the bot is offline and I've waited for at least 30 minutes and it still doesn't work. I wont be active for 14/15 hours as I will be asleep. I will more likely respond then.

**Comment by nsde** [comment]
The project isn't actively maintained at this moment, but @JH220 told me he's planning to work on it again soon.
